dist: xenial
services:
  - xvfb
language: node_js
node_js:
  - "10"
script:
  - npm run check # && npm run test-selenium
after_success:
  - "cat coverage/lcov.info | coveralls --verbose"
cache:
  directories:
  - $HOME/.npm
  - node_modules
addons:
  firefox: "latest"
